In [1]:
import seaborn as sns
import pandas as pd
from scipy.stats import f_oneway

In [2]:
df = sns.load_dataset('titanic')

In [3]:
df[['age','pclass']].isnull().sum()

age       177
pclass      0
dtype: int64

In [4]:
df = df[['age','pclass']].dropna()

In [5]:
class_1 = df[df['pclass']==1]['age']
class_2 = df[df['pclass']==2]['age']
class_3 = df[df['pclass']==3]['age']

In [6]:
df.head()

    age  pclass
0  22.0       3
1  38.0       1
2  26.0       3
3  35.0       1
4  35.0       3

In [7]:
f_stats,p_value = f_oneway(class_1,class_2,class_3)

In [8]:
alpha = 0.05

In [9]:
f_stats

57.443484340676214

In [10]:
p_value

7.487984171959904e-24

In [11]:
if p_value < alpha:
    print('we reject null hypothesis thus significant relationship exists')
else:
    print('there is no significant difference')

we reject null hypothesis thus significant relationship exists

In [12]:
class_1

1      38.0
3      35.0
6      54.0
11     58.0
23     28.0
       ...
871    47.0
872    33.0
879    56.0
887    19.0
889    26.0
Name: age, Length: 186, dtype: float64

In [13]:
df

      age  pclass
0    22.0       3
1    38.0       1
2    26.0       3
3    35.0       1
4    35.0       3
..    ...     ...
885  39.0       3
886  27.0       2
887  19.0       1
889  26.0       1
890  32.0       3

[714 rows x 2 columns]